### PR TITLE
typo: replace typo "an" with "a"

### PR DESCRIPTION
**Pull request by Alan-MQ**
Typo Fix #

fix typo in the comment, replace an with a.
RELEASE NOTES: NONE

### CODE REVIEW

**Review by WineChord — APPROVED** [review]
LGTM

**Comment by WineChord** [comment]
@Alan-MQ  CLA check not passed.

**Comment by Alan-MQ** [comment]
recheck

**Comment by Alan-MQ** [comment]
> @Alan-MQ CLA check not passed.

"I wanted to let you know that I've managed to pass the CLA check. Thank you for your time and assistance."

**Review by WineChord — APPROVED** [review]
LGTM

**Comment by WineChord** [comment]
cc @sandyskies for final merge.

**Pull request merged**
