### PR TITLE
{client, naming}: allow selector to define its own net.Addr parser

### PR DESCRIPTION
**Pull request by YoungFr**
This is used to avoid unnecessary addr parse which is commonly used
in trpc-database.

To properly update the DSN library, we need to introduce this feature into
the open-source tRPC-Go.

RELEASE NOTES: NONE

### CODE REVIEW

**Comment by YoungFr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by liuzengh** [comment]
@sandyskies  need realse a new version after this pr be merged.

**Comment by sandyskies** [comment]
Pls update the pr description @YoungFr

**Comment by YoungFr** [comment]
> Pls update the pr description @YoungFr

done

**Pull request merged**
