### PR TITLE
gomod: upgrade golang.org/x/net to latest version

### PR DESCRIPTION
**Pull request by WineChord**
https://github.com/trpc-group/trpc-go/security

### CODE REVIEW

**Comment by WineChord** [comment]
Why has the code coverage decreased when I have only made changes to go.mod and go.sum files? 🙁

**Comment by sandyskies** [comment]
@WineChord check this https://app.codecov.io/gh/trpc-group/trpc-go/pull/106/indirect-changes

**Comment by WineChord** [comment]
I suspect that there might be a degree of randomization in the test cases, which could occasionally lead to variations in code coverage. For instance, in https://github.com/trpc-group/trpc-go/pull/113, despite only making changes to the markdown files, there was still a slight decrease in code coverage.

**Review by liuzengh — APPROVED** [review]
LGTM

**Pull request merged**
